# FROM jupyter/minimal-notebook:latest
# FROM mcranmer/pysr:latest AS sr

# PYSR DOCKERFILE  https://github.com/MilesCranmer/PySR/blob/master/Dockerfile
ARG JLVERSION=1.8.2
ARG PYVERSION=3.10.8
ARG BASE_IMAGE=bullseye

FROM julia:${JLVERSION}-${BASE_IMAGE} AS jl
FROM python:${PYVERSION}-${BASE_IMAGE}

# BINDER INSTRUCTIONS  https://mybinder.readthedocs.io/en/latest/tutorials/dockerfile.html
# START BINDER
ARG NB_USER=ic
ARG NB_UID=1000
ENV USER ${NB_USER}
ENV NB_UID ${NB_UID}
ENV HOME /home/${NB_USER}

RUN adduser --disabled-password \
    --gecos "Default user" \
    --uid ${NB_UID} \
    ${NB_USER}

USER ${NB_USER}
WORKDIR ${HOME}

RUN pwd
RUN ls -lah

# COPY . ${HOME}

# RUN ls -lah ${HOME}

# USER root
# RUN chown -R ${NB_UID} ${HOME}
# USER ${NB_USER}

# add local pip install directory
RUN echo "${HOME}/.local/bin"
ENV PATH="${PATH}:${HOME}/.local/bin"
RUN echo "${PATH}"
# # END BINDER

# Merge Julia image:
COPY --from=jl /usr/local/julia /usr/local/julia
ENV PATH="/usr/local/julia/bin:${PATH}"
RUN echo "${PATH}"

# Install IPython and other useful libraries:
RUN pip3 install -q ipython numpy scipy sympy statsmodels matplotlib lxml pandas jupyterlab jupyterhub

RUN wget -q https://minlp.com/downloads/xecs/alamo/current/alamo-linux64.zip
RUN unzip -q alamo-linux64.zip

RUN ${HOME}/alamo-linux64/alamo --version

ADD https://api.github.com/repos/IlyaOrson/alamopy/git/ref/heads/main /.git-hashref
RUN git clone https://github.com/IlyaOrson/alamopy.git
RUN git clone https://github.com/MilesCranmer/PySR.git

RUN pwd
RUN ls -lah
RUN ls -lah PySR/
RUN ls -lah ${HOME}
RUN ls -lah ${HOME}/PySR/
RUN cat ${HOME}/PySR/requirements.txt

# Caches install (https://stackoverflow.com/questions/25305788/how-to-avoid-reinstalling-packages-when-building-docker-image-for-python-project)
# COPY ${HOME}/PySR/requirements.txt ${HOME}/requirements.txt
RUN mv ${HOME}/PySR/requirements.txt ${HOME}/requirements.txt
RUN pip3 install -r ${HOME}/requirements.txt

# Install PySR:
# We do a minimal copy so it doesn't need to rerun at every file change:
# COPY ${HOME}/PySR/setup.py ${HOME}/setup.py
# COPY ${HOME}/PySR/pysr/ ${HOME}/pysr/
RUN mv ${HOME}/PySR/setup.py ${HOME}/setup.py
RUN mv ${HOME}/PySR/pysr/ ${HOME}/pysr/
RUN pip3 install .

# Install Julia pre-requisites:
RUN python3 -c 'import pysr; pysr.install()'

RUN mv ${HOME}/alamopy/ ${HOME}/alamopy_repo
RUN mv ${HOME}/alamopy_repo/alamopy/ ${HOME}/alamopy
RUN mv ${HOME}/alamopy_repo/demo.ipynb ${HOME}/demo.ipynb

RUN ls -lah

# ENTRYPOINT python3 -m jupyter lab --ip 0.0.0.0 --port 8888 --no-browser --allow-root
